//! The audit module records accepted, rejected, and completed facts for control commands.
//!
//! The first version does not introduce a persistent database, so audit events are stored in an in-memory recorder and can continue to fan out through the event stream.

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;
use uuid::Uuid;

use crate::auth::RemoteIdentity;
use crate::command::PreparedCommand;

/// `AuditResult` represents the audit fact for a command at a certain stage.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AuditResult {
    /// `Accepted` indicates that the relay accepted the command and is ready to forward it.
    Accepted,
    /// `Rejected` indicates that the relay or target process rejected the command.
    Rejected,
    /// `Completed` indicates that the target process returned a completed result.
    Completed,
}

/// `AuditEvent` stores the identity, target, reason, and result for a control command.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuditEvent {
    /// `audit_id` is the unique identifier generated by the relay.
    pub audit_id: Uuid,
    /// `identity_principal` is the operator or service identity that executed the command.
    pub identity_principal: String,
    /// `target_id` is the target process identity.
    pub target_id: String,
    /// `command_id` is the client command identifier.
    pub command_id: String,
    /// `command` is the control command name.
    pub command: String,
    /// `target` is the object affected by the command.
    pub target: Option<String>,
    /// `reason` is the reason entered by the operator.
    pub reason: String,
    /// `result` is accepted, rejected, or completed.
    pub result: AuditResult,
    /// `detail` stores the rejection reason or completion summary.
    pub detail: String,
    /// `occurred_at` is the audit event time.
    pub occurred_at: OffsetDateTime,
}

/// `AuditRecorder` stores in-memory audit events.
#[derive(Debug, Default)]
pub struct AuditRecorder {
    /// `events` stores recorded audit events.
    events: Vec<AuditEvent>,
}

impl AuditRecorder {
    /// Records an accepted audit event.
    ///
    /// The `identity` parameter is the authenticated remote identity.
    /// The `command` parameter is the validated control command.
    /// The `now` parameter is the audit time.
    pub fn record_accepted(
        &mut self,
        identity: &RemoteIdentity,
        command: &PreparedCommand,
        now: OffsetDateTime,
    ) {
        self.record(identity, command, AuditResult::Accepted, "accepted", now);
    }

    /// Records a rejected audit event.
    ///
    /// The `identity` parameter is the authenticated remote identity.
    /// The `command` parameter is the validated control command.
    /// The `detail` parameter is the rejection reason.
    /// The `now` parameter is the audit time.
    pub fn record_rejected(
        &mut self,
        identity: &RemoteIdentity,
        command: &PreparedCommand,
        detail: impl Into<String>,
        now: OffsetDateTime,
    ) {
        self.record(identity, command, AuditResult::Rejected, detail, now);
    }

    /// Records a completed audit event.
    ///
    /// The `identity` parameter is the authenticated remote identity.
    /// The `command` parameter is the validated control command.
    /// The `detail` parameter is the completion summary.
    /// The `now` parameter is the audit time.
    pub fn record_completed(
        &mut self,
        identity: &RemoteIdentity,
        command: &PreparedCommand,
        detail: impl Into<String>,
        now: OffsetDateTime,
    ) {
        self.record(identity, command, AuditResult::Completed, detail, now);
    }

    /// Reads all audit events.
    ///
    /// This method has no parameters because it reads the current recorder memory.
    /// The return value is the audit event slice stored in write order.
    pub fn events(&self) -> &[AuditEvent] {
        &self.events
    }

    /// Writes one audit event.
    ///
    /// The `identity` parameter is the authenticated remote identity.
    /// The `command` parameter is the validated control command.
    /// The `result` parameter is the audit result.
    /// The `detail` parameter is the audit detail.
    /// The `now` parameter is the audit time.
    fn record(
        &mut self,
        identity: &RemoteIdentity,
        command: &PreparedCommand,
        result: AuditResult,
        detail: impl Into<String>,
        now: OffsetDateTime,
    ) {
        self.events.push(AuditEvent {
            audit_id: Uuid::new_v4(),
            identity_principal: identity.principal.clone(),
            target_id: command.target_id.clone(),
            command_id: command.command_id.clone(),
            command: format!("{:?}", command.command),
            target: command.target.child_path.clone(),
            reason: command.reason.clone(),
            result,
            detail: detail.into(),
            occurred_at: now,
        });
    }
}
