//! The command module validates control commands sent by the dashboard.
//!
//! The relay derives `requested_by`, rejects historical command aliases, and refuses dangerous commands without confirmation.

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

use crate::auth::RemoteIdentity;
use crate::error::{RelayError, RelayResult};

/// `ControlCommandName` enumerates the commands allowed in the first version.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ControlCommandName {
    /// `RestartChild` restarts a child task.
    RestartChild,
    /// `PauseChild` pauses a child task.
    PauseChild,
    /// `ResumeChild` resumes a child task.
    ResumeChild,
    /// `QuarantineChild` quarantines a child task.
    QuarantineChild,
    /// `RemoveChild` removes a child task.
    RemoveChild,
    /// `AddChild` adds a child task.
    AddChild,
    /// `ShutdownTree` shuts down the whole supervisor tree.
    ShutdownTree,
}

impl ControlCommandName {
    /// Parses a control command name from a wire string.
    ///
    /// The `value` parameter is the command name from the client message.
    /// The return value is the allowed command enum, or a structured rejection for legacy aliases and unknown commands.
    pub fn from_wire(value: &str) -> RelayResult<Self> {
        match value {
            "restart_child" => Ok(Self::RestartChild),
            "pause_child" => Ok(Self::PauseChild),
            "resume_child" => Ok(Self::ResumeChild),
            "quarantine_child" => Ok(Self::QuarantineChild),
            "remove_child" => Ok(Self::RemoveChild),
            "add_child" => Ok(Self::AddChild),
            "shutdown_tree" => Ok(Self::ShutdownTree),
            _ => Err(RelayError::new(
                "unsupported_method",
                "command_parse",
                None,
                "unknown command or historical command alias is not supported",
                false,
            )),
        }
    }

    /// Returns the stable wire name used by the command.
    ///
    /// This method has no parameters because the name only depends on the current enum value.
    /// The return value is the command name.
    pub fn wire_name(self) -> &'static str {
        match self {
            Self::RestartChild => "restart_child",
            Self::PauseChild => "pause_child",
            Self::ResumeChild => "resume_child",
            Self::QuarantineChild => "quarantine_child",
            Self::RemoveChild => "remove_child",
            Self::AddChild => "add_child",
            Self::ShutdownTree => "shutdown_tree",
        }
    }

    /// Determines whether the command requires secondary confirmation.
    ///
    /// This method has no parameters because it only reads the current command enum.
    /// The return value indicates whether the command is dangerous.
    pub fn requires_confirmation(self) -> bool {
        matches!(
            self,
            Self::ShutdownTree | Self::RemoveChild | Self::AddChild
        )
    }
}

/// `CommandTarget` stores the child path affected by a control command.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CommandTarget {
    /// `child_path` is the target child task path and can be empty when shutting down the supervision tree.
    pub child_path: Option<String>,
}

/// `ClientCommand` represents a raw control message sent by the dashboard.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClientCommand {
    /// `command_id` is the idempotency identifier generated by the client.
    pub command_id: String,
    /// `correlation_id` is only used for trace correlation or UI display.
    pub correlation_id: Option<String>,
    /// `target_id` is the target process identity.
    pub target_id: String,
    /// `command` is the allowed control command name.
    pub command: ControlCommandName,
    /// `target` is the child task or supervision tree affected by the command.
    pub target: CommandTarget,
    /// `reason` is the non-empty reason entered by the operator.
    pub reason: String,
    /// `confirmed` indicates whether a dangerous command has completed secondary confirmation.
    pub confirmed: bool,
    /// `requested_by` is a field that clients must not provide. The relay rejects overrides.
    pub requested_by: Option<String>,
}

/// `PreparedCommand` is a control command validated by the relay with identity bound.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PreparedCommand {
    /// `command_id` is the idempotency identifier generated by the client.
    pub command_id: String,
    /// `correlation_id` is only used for trace correlation or UI display.
    pub correlation_id: Option<String>,
    /// `target_id` is the target process identity.
    pub target_id: String,
    /// `command` is the allowed control command name.
    pub command: ControlCommandName,
    /// `target` is the child task or supervision tree affected by the command.
    pub target: CommandTarget,
    /// `reason` is the non-empty reason entered by the operator.
    pub reason: String,
    /// `requested_by` is the identity derived by the relay from `RemoteIdentity`.
    pub requested_by: String,
    /// `confirmed` indicates whether a dangerous command has completed secondary confirmation.
    pub confirmed: bool,
    /// `requested_at` is the time when the relay accepted the command.
    pub requested_at: OffsetDateTime,
}

/// `ControlCommandResult` stores the execution result returned by target IPC.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ControlCommandResult {
    /// `command_id` is the client command identifier.
    pub command_id: String,
    /// `correlation_id` is only used for trace correlation or UI display.
    pub correlation_id: Option<String>,
    /// `target_id` is the target process identity.
    pub target_id: String,
    /// `accepted` indicates whether the target process accepted the command.
    pub accepted: bool,
    /// `status` is `accepted`, `rejected`, `completed`, or `failed`.
    pub status: String,
    /// `requested_by` is the identity derived by the relay.
    pub requested_by: String,
    /// `completed_at` is the command result time.
    pub completed_at: OffsetDateTime,
}

/// Validates a client command and derives `requested_by`.
///
/// The `command` parameter is the raw command sent by the dashboard.
/// The `identity` parameter is the authenticated remote identity.
/// The `now` parameter is the request time.
/// The return value is the command that can be forwarded to target IPC, or a structured rejection error.
pub fn prepare_client_command(
    command: ClientCommand,
    identity: &RemoteIdentity,
    now: OffsetDateTime,
) -> RelayResult<PreparedCommand> {
    if command.command_id.trim().is_empty() {
        return Err(RelayError::for_target(
            "invalid_message_schema",
            "command_validate",
            command.target_id,
            "command_id must not be empty",
            false,
        ));
    }

    if command.requested_by.is_some() {
        return Err(RelayError::for_target(
            "requested_by_override",
            "command_validate",
            command.target_id,
            "client must not provide requested_by",
            false,
        ));
    }

    if command.reason.trim().is_empty() {
        return Err(RelayError::for_target(
            "empty_reason",
            "command_validate",
            command.target_id,
            "command reason must not be empty",
            false,
        ));
    }

    if command.command.requires_confirmation() && !command.confirmed {
        return Err(RelayError::for_target(
            "confirmation_required",
            "command_validate",
            command.target_id,
            "dangerous command requires confirmed=true",
            false,
        ));
    }

    Ok(PreparedCommand {
        command_id: command.command_id,
        correlation_id: command.correlation_id,
        target_id: command.target_id,
        command: command.command,
        target: command.target,
        reason: command.reason,
        requested_by: identity.principal.clone(),
        confirmed: command.confirmed,
        requested_at: now,
    })
}
